package com.zuovx.book.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book
 */
public class Book {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   更改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * Database Column Remarks:
     *   书名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbg.generated
     */
    private String bookName;

    /**
     * Database Column Remarks:
     *   书本图片url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_image_url
     *
     * @mbg.generated
     */
    private String bookImageUrl;

    /**
     * Database Column Remarks:
     *   书本描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_describe
     *
     * @mbg.generated
     */
    private String bookDescribe;

    /**
     * Database Column Remarks:
     *   类别id，数据字典
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     * Database Column Remarks:
     *   所属用户的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   0自己的 1换的 2赠的 3借的
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.kind
     *
     * @mbg.generated
     */
    private Byte kind;

    /**
     * Database Column Remarks:
     *   0否 1是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.is_deleted
     *
     * @mbg.generated
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_id
     *
     * @return the value of book.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_id
     *
     * @param bookId the value for book.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.created_at
     *
     * @return the value of book.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.created_at
     *
     * @param createdAt the value for book.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.update_at
     *
     * @return the value of book.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.update_at
     *
     * @param updateAt the value for book.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbg.generated
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbg.generated
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_image_url
     *
     * @return the value of book.book_image_url
     *
     * @mbg.generated
     */
    public String getBookImageUrl() {
        return bookImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_image_url
     *
     * @param bookImageUrl the value for book.book_image_url
     *
     * @mbg.generated
     */
    public void setBookImageUrl(String bookImageUrl) {
        this.bookImageUrl = bookImageUrl == null ? null : bookImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_describe
     *
     * @return the value of book.book_describe
     *
     * @mbg.generated
     */
    public String getBookDescribe() {
        return bookDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_describe
     *
     * @param bookDescribe the value for book.book_describe
     *
     * @mbg.generated
     */
    public void setBookDescribe(String bookDescribe) {
        this.bookDescribe = bookDescribe == null ? null : bookDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.category_id
     *
     * @return the value of book.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.category_id
     *
     * @param categoryId the value for book.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.user_id
     *
     * @return the value of book.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.user_id
     *
     * @param userId the value for book.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.kind
     *
     * @return the value of book.kind
     *
     * @mbg.generated
     */
    public Byte getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.kind
     *
     * @param kind the value for book.kind
     *
     * @mbg.generated
     */
    public void setKind(Byte kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.is_deleted
     *
     * @return the value of book.is_deleted
     *
     * @mbg.generated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.is_deleted
     *
     * @param isDeleted the value for book.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}