package com.zuovx.book.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table desire
 */
public class Desire {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column desire.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column desire.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   更改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column desire.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * Database Column Remarks:
     *   意愿标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column desire.desire_title
     *
     * @mbg.generated
     */
    private String desireTitle;

    /**
     * Database Column Remarks:
     *   意愿内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column desire.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   所属用户的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column desire.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   0换 1借 2赠 3送
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column desire.kind
     *
     * @mbg.generated
     */
    private Byte kind;

    /**
     * Database Column Remarks:
     *   0否 1是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column desire.is_deleted
     *
     * @mbg.generated
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column desire.id
     *
     * @return the describe of desire.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column desire.id
     *
     * @param id the describe for desire.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column desire.created_at
     *
     * @return the describe of desire.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column desire.created_at
     *
     * @param createdAt the describe for desire.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column desire.update_at
     *
     * @return the describe of desire.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column desire.update_at
     *
     * @param updateAt the describe for desire.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column desire.desire_title
     *
     * @return the describe of desire.desire_title
     *
     * @mbg.generated
     */
    public String getDesireTitle() {
        return desireTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column desire.desire_title
     *
     * @param desireTitle the describe for desire.desire_title
     *
     * @mbg.generated
     */
    public void setDesireTitle(String desireTitle) {
        this.desireTitle = desireTitle == null ? null : desireTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column desire.content
     *
     * @return the describe of desire.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column desire.content
     *
     * @param content the describe for desire.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column desire.user_id
     *
     * @return the describe of desire.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column desire.user_id
     *
     * @param userId the describe for desire.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column desire.kind
     *
     * @return the describe of desire.kind
     *
     * @mbg.generated
     */
    public Byte getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column desire.kind
     *
     * @param kind the describe for desire.kind
     *
     * @mbg.generated
     */
    public void setKind(Byte kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column desire.is_deleted
     *
     * @return the describe of desire.is_deleted
     *
     * @mbg.generated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column desire.is_deleted
     *
     * @param isDeleted the describe for desire.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}