package com.zuovx.book.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table friend_group
 */
public class FriendGroup {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_group.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_group.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   更改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_group.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_group.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   分组名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_group.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   0否 1是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_group.is_deleted
     *
     * @mbg.generated
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column friend_group.id
     *
     * @return the describe of friend_group.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column friend_group.id
     *
     * @param id the describe for friend_group.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column friend_group.created_at
     *
     * @return the describe of friend_group.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column friend_group.created_at
     *
     * @param createdAt the describe for friend_group.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column friend_group.update_at
     *
     * @return the describe of friend_group.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column friend_group.update_at
     *
     * @param updateAt the describe for friend_group.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column friend_group.user_id
     *
     * @return the describe of friend_group.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column friend_group.user_id
     *
     * @param userId the describe for friend_group.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column friend_group.name
     *
     * @return the describe of friend_group.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column friend_group.name
     *
     * @param name the describe for friend_group.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column friend_group.is_deleted
     *
     * @return the describe of friend_group.is_deleted
     *
     * @mbg.generated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column friend_group.is_deleted
     *
     * @param isDeleted the describe for friend_group.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}