package com.zuovx.book.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table message
 */
public class Message {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   更改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.update_at
     *
     * @mbg.generated
     */
    private Date updateAt;

    /**
     * Database Column Remarks:
     *   内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.text
     *
     * @mbg.generated
     */
    private String text;

    /**
     * Database Column Remarks:
     *   发送者id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.from_user_id
     *
     * @mbg.generated
     */
    private Integer fromUserId;

    /**
     * Database Column Remarks:
     *   接收者id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.to_user_id
     *
     * @mbg.generated
     */
    private Integer toUserId;

    /**
     * Database Column Remarks:
     *   0文本 1 图片 如果是图片，则text放图片url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_type
     *
     * @mbg.generated
     */
    private Byte messageType;

    /**
     * Database Column Remarks:
     *   0否 1是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_deleted
     *
     * @mbg.generated
     */
    private Byte isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column message.id
     *
     * @return the describe of message.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column message.id
     *
     * @param id the describe for message.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column message.created_at
     *
     * @return the describe of message.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column message.created_at
     *
     * @param createdAt the describe for message.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column message.update_at
     *
     * @return the describe of message.update_at
     *
     * @mbg.generated
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column message.update_at
     *
     * @param updateAt the describe for message.update_at
     *
     * @mbg.generated
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column message.text
     *
     * @return the describe of message.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column message.text
     *
     * @param text the describe for message.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column message.from_user_id
     *
     * @return the describe of message.from_user_id
     *
     * @mbg.generated
     */
    public Integer getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column message.from_user_id
     *
     * @param fromUserId the describe for message.from_user_id
     *
     * @mbg.generated
     */
    public void setFromUserId(Integer fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column message.to_user_id
     *
     * @return the describe of message.to_user_id
     *
     * @mbg.generated
     */
    public Integer getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column message.to_user_id
     *
     * @param toUserId the describe for message.to_user_id
     *
     * @mbg.generated
     */
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column message.message_type
     *
     * @return the describe of message.message_type
     *
     * @mbg.generated
     */
    public Byte getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column message.message_type
     *
     * @param messageType the describe for message.message_type
     *
     * @mbg.generated
     */
    public void setMessageType(Byte messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the describe of the database column message.is_deleted
     *
     * @return the describe of message.is_deleted
     *
     * @mbg.generated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the describe of the database column message.is_deleted
     *
     * @param isDeleted the describe for message.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}