package com.zuovx.book.dao;

import com.zuovx.book.model.FriendGroup;
import com.zuovx.book.model.FriendGroupExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface FriendGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated
     */
    long countByExample(FriendGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated
     */
    int deleteByExample(FriendGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated
     */
    int insert(FriendGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated
     */
    int insertSelective(FriendGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated
     */
    List<FriendGroup> selectByExample(FriendGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated
     */
    FriendGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FriendGroup record, @Param("example") FriendGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FriendGroup record, @Param("example") FriendGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FriendGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FriendGroup record);
}